version: '3.4'
services:
  swarm:
    image: parrots9/rpcserver
    deploy:
      replicas: 1
      update_config:
        parallelism: 1
        delay: 1s
        order: start-first
      restart_policy:
        condition: on-failure
    ports:
      - 4466:4466
    command: ["/bin/main"]